name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      
    steps:
    - uses: actions/checkout@v4

    - name: Build and run Docker containers
      run: docker-compose -f docker-compose.dev.yml up --build -d
