name: Jenkins Build Hook

on:
  pull_request:
    types: 
      - closed
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "${{ secrets.JENKINS_HOST_URL }}/job/ASE-Pipeline/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}"
        user: "zetioz"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "ASE-Pipeline"
