name: Jenkins Build Hook

on:
  pull_request:
    types:
      - closed
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins build
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.donatog.tech"
        user: "zetioz"
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "ASE-Pipeline"
