name: Set Label and Project for New Issue

on:
  issues:
    types:
      - opened

jobs:
  set-label-and-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Label and Project
        run: |
          # Get the issue number
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")

          # Set label for the new issue
          echo "Setting label for issue $ISSUE_NUMBER"
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
            -d '["your-label-name"]'

          # Set project for the new issue
          echo "Setting project for issue $ISSUE_NUMBER"
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/projects/columns/${{ secrets.PROJECT_COLUMN_ID }}/cards \
            -d '{"content_id":'$ISSUE_NUMBER',"content_type":"Issue"}'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
