name: Set Label and Project for New Issue

on:
  issues:
    types:
      - opened

jobs:
  set-label-and-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Label
        run: |
          # Get the issue number
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")

          # Set label for the new issue
          echo "Setting label for issue $ISSUE_NUMBER"
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
            -d '["triage"]'
        
      - name: Set Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/UNamurCSFaculty/projects/10
          github-token: ${{ secrets.ISSUE_KEY }}
